error: Introduce causer interface
This introduces a causer interface for communicating the cause of an
error and modifies RootCause to use that.

We need to use this interface to add richer error types with more
information instead of our current approach of using wrappedError
everywhere which gives us nothing but a string.